# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dependencies
    init: |
      cd ./server
      npm install
      cd ../web
      npm install
    env:
      DATABASE_URL: "file:./dev.db"

  - name: DB
    command: |
      cd ./server
      npm run db

  - name: Back End
    command: |
      cd ./server
      npm run dev
      
  - name: Front End
    command: |
      cd ./web
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5555
    onOpen: open-browser
  - port: 3333
    onOpen: open-preview
  - port: 3000
    onOpen: open-browser
