# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Back End
    init: >
      cd ./server && 
      npm install
    command: >
      cd ./server && 
      npm run dev
      
  - name: Front End
    init: >
      cd ./web && 
      npm install
    command: >
      cd ./web && 
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3333
    onOpen: open-preview
  - port: 3000
    onOpen: open-browser
