# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dependencies
    init: |
      cd ./server
      mv ./prisma/schema.prisma ./prisma/schema.prod.prisma
      mv ./prisma/schema.dev.prisma ./prisma/schema.prisma
      npm install
      cd ../web
      npm install
      npm install vite -g
      gp sync-done dependencies

  - name: DB
    init: gp sync-await dependencies
    command: |
      cd ./server
      npm run db -y

  - name: Back End
    env:
      ECHO_WEB_URL: echo $(gp url 3000)
    init: |
      gp sync-await dependencies
      echo "$(eval $ECHO_WEB_URL)"
      eval $(gp env -e VITE_WEB_URL="$(eval $ECHO_WEB_URL)")
    command: |
      cd ./server
      npm run build
      npm start

  - name: Front End
    env:
      ECHO_API_URL: echo $(gp url 3333)
    init: |
      gp sync-await dependencies
      echo "$(eval $ECHO_API_URL)"
      eval $(gp env -e VITE_API_URL="$(eval $ECHO_API_URL)")
    command: |
      cd ./web
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5555
    onOpen: open-browser
  - port: 3333
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - rangav.vscode-thunder-client
