# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dependencies
    init: |
      cd ./server
      mv ./prisma/schema.prisma ./prisma/schema.prod.prisma
      mv ./prisma/schema.dev.prisma ./prisma/schema.prisma
      npm install
      cd ../web
      npm install
      echo 'DATABASE_URL: ' $DATABASE_URL

  - name: DB
    command: |
      cd ./server
      npm run db -y

  - name: Back End
    command: |
      cd ./server
      npm run build
      npm start

  - name: Front End
    command: |
      cd ./web
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5555
    onOpen: open-browser
  - port: 3333
    onOpen: open-browser
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - rangav.vscode-thunder-client
